[package]
name = "rustshop"
version = "0.1.0"
edition = "2021"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
description = "A tool for bootstrapping and operating cloud based software shops infrastructure"
documentation = "https://github.com/rustshop/rustshop"
homepage = "https://github.com/rustshop/rustshop"
repository = "https://github.com/rustshop/rustshop"
keywords = ["kubernetes", "infra", "cloud"]
license = "MPL-2.0"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1.35"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
rustshop-env = { version = "*", path = "../env/" }
clap = { version = "3.1.6", features = [ "derive", "env" ] }
clap_complete = "3.2.3"
error-stack = { version = "0.4.1", default-features = false, features = [ "std" ] }
derive_more = "0.99.17"
serde = "1.0.138"
serde_json = "1.0.82"
tempfile = "3.3.0"
rand = "0.8.5"
